import QRCode from 'qrcode';

export interface SeventeenPointItem {
  pointNumber: number;
  label: string;
  value: string;
}

export interface VerificationSummaryItem {
  label: string;
  value: string;
}

export interface AdmissionVerificationPayload {
  recordNumber: string;
  verificationId: string;
  consentReferenceNumber: string;
  consentCertificationId: string;
  sealRegistrationNumber: string;
  departmentalRecordNumber: string;
  oathRegistrationDate: string;
  verifiedContact: string;
  verificationDateIst: string;
  verificationTimeIst: string;
   verifiedAtIso: string;
  consentStatus: string;
  oathStatus: string;
  otpStatus: string;
  admissionDate: string;
  courseClass: string;
  verifiedAt: string;
  interviewSerialNumber: string; // Question No. 43
  // The 17 points for Email & QR Code
  applicantName: string; // Point 2
  enrollmentDate: string; // Point 41
  srNumber: string; // Point 44
  registrationNumber: string; // Point 45
  enrollmentNumber: string; // Point 46
  totalActiveApplicantNumber: string; // Point 50
  applicantAllottedNumber: string; // Point 51
  enrollmentCollectNumber: string; // Point 52
  packageDuration: string; // Point 64
  clap: string; // Point 75
  clapName: string; // Point 77
  clapSubjectName: string; // Point 78
  finalPayableFees: string; // Point 110
  oathCertificationNumber: string; // Point 121
  deponentName: string; // Point 122
  oathNumber: string; // Point 127
  consentNumber: string; // Point 128
  seventeenPoints: SeventeenPointItem[];
  summaryIdentifiers: VerificationSummaryItem[];
}

export function formatIstDateTime(isoOrDateStr?: string): {
  dateIst: string;
  timeIst: string;
  fullIst: string;
} {
  let d = new Date();
  if (isoOrDateStr) {
    const parsed = new Date(isoOrDateStr);
    if (!isNaN(parsed.getTime())) {
      d = parsed;
    }
  }
  try {
    const dateIst = d.toLocaleDateString('en-IN', {
      timeZone: 'Asia/Kolkata',
      day: '2-digit',
      month: 'short',
      year: 'numeric',
    });
    const timeIst =
      d.toLocaleTimeString('en-IN', {
        timeZone: 'Asia/Kolkata',
        hour: '2-digit',
        minute: '2-digit',
        second: '2-digit',
        hour12: true,
      }) + ' IST';
    return {
      dateIst,
      timeIst,
      fullIst: `${dateIst}, ${timeIst}`,
    };
  } catch {
    const fallback = d.toISOString().replace('T', ' ').slice(0, 19) + ' IST';
    return {
      dateIst: fallback.slice(0, 10),
      timeIst: fallback.slice(11),
      fullIst: fallback,
    };
  }
}

/**
 * Extracts a single consistent verified data snapshot from the form answers
 * (with fallback to live DOM input elements if needed).
 * Used identically across Confirmation Email, QR Code, Round Seal, and Record Summary.
 */
export function extractVerificationPayload(
  recordNumber: string,
  answers: Record<string, string | string[]>,
  fallbackVerifiedAtIso?: string,
  explicitVerifiedContact?: string
): AdmissionVerificationPayload {
  const str = (...keys: string[]): string => {
    for (const key of keys) {
      const val = answers[key];
      if (Array.isArray(val)) {
        const joined = val.filter((v) => String(v).trim() !== '').join(', ').trim();
        if (joined) return joined;
      } else if (typeof val === 'string' && val.trim() !== '') {
        return val.trim();
      }
      if (typeof document !== 'undefined') {
        const el = document.getElementById(`input-${key}`) as
          | HTMLInputElement
          | HTMLSelectElement
          | HTMLTextAreaElement
          | null;
        if (el && typeof el.value === 'string' && el.value.trim() !== '') {
          return el.value.trim();
        }
      }
    }
    return '';
  };

  const rawVerifiedVal = str('q171');
  const idMatch = rawVerifiedVal.match(/(NVEA-(?:OTP|GAS)-[A-Z0-9]+)/i);
  const cleanRec = recordNumber.replace(/[^A-Z0-9]/gi, '');
  const verificationId = idMatch ? idMatch[1].toUpperCase() : `NVEA-OTP-${cleanRec}`;

  const emailMatch = rawVerifiedVal.match(/\(([^•)]+@[^•)]+)/);
  const verifiedContact =
    (explicitVerifiedContact && explicitVerifiedContact.trim()) ||
    (emailMatch ? emailMatch[1].trim() : '') ||
    '';

  const verifiedIso = fallbackVerifiedAtIso || new Date().toISOString();
  const { dateIst, timeIst } = formatIstDateTime(verifiedIso);

  // Question No. 43 Interview Serial Number (Auto-generated upon OTP verification)
  const cleanNum = cleanRec.replace(/^NVEA/i, '') || cleanRec || `${new Date().getFullYear()}01`;
  const rawIsn = str('q40', 'q130');
  const autoGeneratedIsn = `NVEA-ISN-${cleanNum}`;
  const interviewSerialNumber =
    rawIsn && rawIsn.trim() !== '' && rawIsn.trim() !== '—'
      ? rawIsn.trim()
      : autoGeneratedIsn;

  // Exact points from the form
  const applicantName = str('q2') || '—'; // Point 2
  const enrollmentDate = str('q38', 'q143') || '—'; // Point 41
  const srNumber = str('q41', 'q131') || '—'; // Point 44
  const registrationNumber = str('q42', 'q132') || '—'; // Point 45
  const enrollmentNumber = str('q43', 'q133') || '—'; // Point 46
  const totalActiveApplicantNumber = str('q47', 'q135') || '—'; // Point 50
  const applicantAllottedNumber = str('q48', 'q136') || '—'; // Point 51
  const enrollmentCollectNumber = str('q49', 'q134') || '—'; // Point 52
  const packageDuration = str('q61', 'q148') || '—'; // Point 64
  const clap = str('q72') || '—'; // Point 75
  const clapName = str('q74', 'q145') || '—'; // Point 77
  const clapSubjectName = str('q75', 'q146') || '—'; // Point 78
  const finalPayableFees = str('q107', 'q163') || '—'; // Point 110
  const oathCertificationNumber = str('q118') || '—'; // Point 121
  const deponentName = str('q119') || '—'; // Point 122
  const oathNumber = str('q124') || '—'; // Point 127
  const consentNumber = str('q125') || '—'; // Point 128

  const seventeenPoints: SeventeenPointItem[] = [
    { pointNumber: 2, label: 'Applicant Name', value: applicantName },
    { pointNumber: 41, label: 'Enrollment Date', value: enrollmentDate },
    { pointNumber: 43, label: 'Interview Serial Number', value: interviewSerialNumber },
    { pointNumber: 44, label: 'SR Number', value: srNumber },
    { pointNumber: 45, label: 'Registration Number', value: registrationNumber },
    { pointNumber: 46, label: 'Enrollment Number', value: enrollmentNumber },
    { pointNumber: 50, label: 'Total Active Applicant Number', value: totalActiveApplicantNumber },
    { pointNumber: 51, label: 'Applicant Allotted Number', value: applicantAllottedNumber },
    { pointNumber: 52, label: 'Enrollment Collect Number', value: enrollmentCollectNumber },
    { pointNumber: 64, label: 'Package Duration', value: packageDuration },
    { pointNumber: 75, label: 'CLAP', value: clap },
    { pointNumber: 77, label: 'CLAP Name', value: clapName },
    { pointNumber: 78, label: 'CLAP Subject Name', value: clapSubjectName },
    { pointNumber: 110, label: 'Final Payable Fees', value: finalPayableFees },
    { pointNumber: 121, label: 'Oath Certification Number', value: oathCertificationNumber },
    { pointNumber: 122, label: 'Deponent Name', value: deponentName },
    { pointNumber: 127, label: 'Oath Number', value: oathNumber },
    { pointNumber: 128, label: 'Consent Number', value: consentNumber },
  ];

  // Genuine system-generated verification/authentication/reference identifiers for the Summary Box
  const suffix = verificationId.replace(/^NVEA-(?:OTP|GAS)-/i, '') || cleanRec;
  const consentReferenceNumber = `NVEA-CR-${cleanRec}`;
  const consentCertificationId = `NVEA-CC-${suffix}`;
  const sealRegistrationNumber = `NVEA-SEAL-${cleanRec}`;
  const departmentalRecordNumber = `NVEA-DR-${cleanRec}`;
  const oathRegistrationDate = str('q128') || dateIst;

  const summaryIdentifiers: VerificationSummaryItem[] = [
    { label: 'Point 43 — Interview Serial Number', value: interviewSerialNumber },
    { label: 'Admission / Form Reference ID', value: recordNumber },
    { label: 'OTP Verification ID', value: verificationId },
    { label: 'Consent Reference Number', value: consentReferenceNumber },
    { label: 'Official Consent Certification ID', value: consentCertificationId },
    { label: 'Seal & Stamp Registration No.', value: sealRegistrationNumber },
    { label: 'Departmental Record No.', value: departmentalRecordNumber },
    ...(oathRegistrationDate
      ? [{ label: 'Oath Registration Date', value: oathRegistrationDate }]
      : []),
    ...(verifiedContact
      ? [{ label: 'OTP Verified Gmail ID', value: verifiedContact }]
      : []),
    { label: 'Consent Verification Status', value: 'VERIFIED & CONFIRMED' },
    { label: 'Oath Verification Status', value: 'VERIFIED & APPROVED' },
    { label: 'Gmail / OTP Verification Status', value: 'OTP VERIFIED' },
    { label: 'Verification Date (IST)', value: dateIst },
    { label: 'Verification Time (IST)', value: timeIst },
  ];

  return {
    recordNumber,
    verificationId,
    consentReferenceNumber,
    consentCertificationId,
    sealRegistrationNumber,
    departmentalRecordNumber,
    oathRegistrationDate,
    verifiedContact,
    verificationDateIst: dateIst,
    verificationTimeIst: timeIst,
    verifiedAtIso: verifiedIso,
    consentStatus: 'VERIFIED & CONFIRMED',
    oathStatus: 'VERIFIED & APPROVED',
    otpStatus: 'OTP VERIFIED',
    admissionDate: enrollmentDate !== '—' ? enrollmentDate : dateIst,
    courseClass: clapName !== '—' ? clapName : clap,
    verifiedAt: `${dateIst}, ${timeIst}`,
    interviewSerialNumber,
    applicantName,
    enrollmentDate,
    srNumber,
    registrationNumber,
    enrollmentNumber,
    totalActiveApplicantNumber,
    applicantAllottedNumber,
    enrollmentCollectNumber,
    packageDuration,
    clap,
    clapName,
    clapSubjectName,
    finalPayableFees,
    oathCertificationNumber,
    deponentName,
    oathNumber,
    consentNumber,
    seventeenPoints,
    summaryIdentifiers,
  };
}

/**
 * Builds the HTML body for the Automatic Confirmation Email containing:
 * - Personalized greeting using Point 2 (Applicant Name)
 * - Complete 17-point verified data table (Points 2, 41, 44, 45, 46, 50, 51, 52, 64, 75, 77, 78, 110, 121, 122, 127, 128)
 * - Question No. 43 Interview Serial Number
 * - Official Verification Reference & IST Timestamp summary
 */
export function buildConfirmationEmailHtml(payload: AdmissionVerificationPayload): string {
  const rows17 = payload.seventeenPoints
    .map(
      (pt, idx) => `
      <tr style="background-color: ${idx % 2 === 0 ? '#FFFFFF' : '#F8FAFC'};">
        <td style="padding: 7px 10px; border: 1px solid #CBD5E1; font-weight: bold; color: #0F2942; width: 12%; text-align: center;">Point ${pt.pointNumber}</td>
        <td style="padding: 7px 10px; border: 1px solid #CBD5E1; font-weight: bold; color: #1E293B; width: 42%;">${pt.label}</td>
        <td style="padding: 7px 10px; border: 1px solid #CBD5E1; color: #0F172A; font-family: monospace, sans-serif; font-weight: 600;">${pt.value}</td>
      </tr>`
    )
    .join('');

  return `
    <div style="font-family: Arial, sans-serif; max-width: 660px; margin: 0 auto; border: 2px solid #0F2942; border-radius: 4px; overflow: hidden;">
      <div style="background-color: #0F2942; color: #FFFFFF; padding: 16px 20px; border-bottom: 3px solid #059669;">
        <h2 style="margin: 0; font-size: 17px;">NAND VIDHYA EDUCATION ACADEMY (NVEA / नव्या)</h2>
        <p style="margin: 4px 0 0; font-size: 12px; color: #A7F3D0;">Official Admission &amp; Consent Verification Confirmation</p>
      </div>
      <div style="padding: 20px; color: #0F172A; background-color: #FFFFFF;">
        <p style="margin: 0 0 12px; font-size: 15px;">Dear <strong>${payload.applicantName}</strong>,</p>
        <div style="background-color: #ECFDF5; border: 2px solid #059669; padding: 12px 15px; border-radius: 4px; margin-bottom: 16px;">
          <p style="margin: 0; font-size: 15px; font-weight: bold; color: #065F46;">
            ✓ Your admission and consent have been successfully verified and confirmed through OTP verification.
          </p>
          <p style="margin: 5px 0 0; font-size: 12px; color: #047857;">
            OTP Verification ID: <strong>${payload.verificationId}</strong> &nbsp;|&nbsp; Verified On (IST): <strong>${payload.verificationDateIst}, ${payload.verificationTimeIst}</strong>
          </p>
          <p style="margin: 6px 0 0; font-size: 13px; color: #065F46; font-weight: bold;">
            Point 43 Interview Serial Number: <span style="font-family: monospace, sans-serif; font-size: 13.5px; color: #0F2942; background: #FFFFFF; padding: 2px 7px; border: 1px solid #A7F3D0; border-radius: 3px;">${payload.interviewSerialNumber}</span>
          </p>
        </div>

        <h3 style="margin: 0 0 8px; font-size: 13px; color: #0F2942; text-transform: uppercase; letter-spacing: 0.5px;">
          Official Verified Admission &amp; Consent Data
        </h3>
        <table style="width: 100%; border-collapse: collapse; font-size: 12.5px; margin-bottom: 16px;">
          <thead>
            <tr style="background-color: #0F2942; color: #FFFFFF;">
              <th style="padding: 8px 10px; border: 1px solid #0F2942; text-align: center;">Point No.</th>
              <th style="padding: 8px 10px; border: 1px solid #0F2942; text-align: left;">Field Name</th>
              <th style="padding: 8px 10px; border: 1px solid #0F2942; text-align: left;">Verified Value</th>
            </tr>
          </thead>
          <tbody>
            ${rows17}
          </tbody>
        </table>

        <div style="background-color: #F8FAFC; border: 1px solid #CBD5E1; padding: 10px 14px; border-radius: 3px; font-size: 12px; color: #334155;">
          <strong>Official Verification Reference Summary:</strong><br/>
          • Point 43 Interview Serial Number: <strong style="color: #0F2942; font-family: monospace;">${payload.interviewSerialNumber}</strong><br/>
          • Admission / Form Ref ID: <strong>${payload.recordNumber}</strong><br/>
          • OTP Verification ID: <strong>${payload.verificationId}</strong><br/>
          • Consent Reference No.: <strong>${payload.consentReferenceNumber}</strong><br/>
          • Seal &amp; Stamp Reg. No.: <strong>${payload.sealRegistrationNumber}</strong><br/>
          • Verification Status: <strong style="color: #065F46;">VERIFIED &amp; CONFIRMED (${payload.verificationDateIst} ${payload.verificationTimeIst})</strong>
        </div>
      </div>
      <div style="background-color: #F1F5F9; padding: 10px 20px; font-size: 11px; color: #475569; border-top: 1px solid #CBD5E1;">
        NVEA Official Portal: https://www.nvea.in/ • Helpline: 09414008310
      </div>
    </div>
  `;
}

/**
 * Builds the QR Code content containing ALL 17 verified points
 * (2, 41, 44, 45, 46, 50, 51, 52, 64, 75, 77, 78, 110, 121, 122, 127, 128)
 * plus Question No. 43 Interview Serial Number, official verification reference ID and IST timestamp.
 * Never includes OTP, passwords, or private credentials.
 */
export function buildAdmissionQrContent(payload: AdmissionVerificationPayload): string {
  const lines: string[] = [
    'NAND VIDHYA EDUCATION ACADEMY (NVEA)',
    'STATUS: ADMISSION & CONSENT OTP VERIFIED',
    `Record ID: ${payload.recordNumber}`,
    `OTP Verification ID: ${payload.verificationId}`,
    `Verified (IST): ${payload.verificationDateIst} ${payload.verificationTimeIst}`,
    '--- OFFICIAL VERIFIED ADMISSION DATA ---',
  ];

  payload.seventeenPoints.forEach((pt) => {
    lines.push(`Point ${pt.pointNumber}. ${pt.label}: ${pt.value}`);
  });

  return lines.join('\n');
}

export function buildAdmissionVerifyUrl(payload: AdmissionVerificationPayload): string {
  const origin =
    typeof window !== 'undefined' && window.location?.origin && window.location.origin !== 'null'
      ? window.location.origin
      : 'https://www.nvea.in';

  return `${origin}/?verify=${encodeURIComponent(payload.recordNumber)}`;
}

export async function generateAdmissionQrDataUrl(
  payload: AdmissionVerificationPayload
): Promise<string> {
  const qrText = buildAdmissionQrContent(payload);
  try {
    return await QRCode.toDataURL(qrText, {
      errorCorrectionLevel: 'M',
      margin: 1,
      width: 340,
      color: {
        dark: '#0F2942',
        light: '#FFFFFF',
      },
    });
  } catch {
    return '';
  }
}

/**
 * Generates a high-resolution transparent PNG of the Official NVEA Admission Confirmation
 * & OTP Verified circular institutional rubber stamp/seal.
 * Preserves the exact existing round seal design, colors, border, font appearance, and format.
 */
export function generateAdmissionConfirmedSealPng(
  payload: AdmissionVerificationPayload
): string {
  if (typeof document === 'undefined') return '';
  const size = 460;
  const canvas = document.createElement('canvas');
  canvas.width = size;
  canvas.height = size;
  const ctx = canvas.getContext('2d');
  if (!ctx) return '';

  const cx = size / 2;
  const cy = size / 2;

  ctx.clearRect(0, 0, size, size);
  ctx.save();

  // Slight authentic rubber-stamp rotation (-5 degrees)
  ctx.translate(cx, cy);
  ctx.rotate((-5 * Math.PI) / 180);
  ctx.translate(-cx, -cy);

  // Soft inner tint
  ctx.fillStyle = 'rgba(245, 243, 255, 0.78)';
  ctx.beginPath();
  ctx.arc(cx, cy, 208, 0, Math.PI * 2);
  ctx.fill();

  // Outer scalloped / double institutional purple-indigo border (#5B21B6 / #1E3A8A)
  ctx.strokeStyle = '#5B21B6';
  ctx.lineWidth = 8;
  ctx.beginPath();
  ctx.arc(cx, cy, 206, 0, Math.PI * 2);
  ctx.stroke();

  ctx.strokeStyle = '#1E3A8A';
  ctx.lineWidth = 2.5;
  ctx.beginPath();
  ctx.arc(cx, cy, 194, 0, Math.PI * 2);
  ctx.stroke();

  // Inner concentric ring
  ctx.strokeStyle = '#5B21B6';
  ctx.lineWidth = 3;
  ctx.beginPath();
  ctx.arc(cx, cy, 140, 0, Math.PI * 2);
  ctx.stroke();

  ctx.setLineDash([5, 4]);
  ctx.strokeStyle = '#008FD5';
  ctx.lineWidth = 1.5;
  ctx.beginPath();
  ctx.arc(cx, cy, 132, 0, Math.PI * 2);
  ctx.stroke();
  ctx.setLineDash([]);

  // Draw curved text helper
  const drawCurvedText = (
    text: string,
    radius: number,
    startAngle: number,
    endAngle: number,
    bottom = false
  ) => {
    ctx.save();
    ctx.font = 'bold 17px "Plus Jakarta Sans", Georgia, serif';
    ctx.fillStyle = '#4C1D95';
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    const chars = text.split('');
    const angleSpan = endAngle - startAngle;
    const step = chars.length > 1 ? angleSpan / (chars.length - 1) : 0;

    chars.forEach((ch, idx) => {
      const angle = startAngle + idx * step;
      ctx.save();
      ctx.translate(cx + Math.cos(angle) * radius, cy + Math.sin(angle) * radius);
      ctx.rotate(bottom ? angle - Math.PI / 2 : angle + Math.PI / 2);
      ctx.fillText(ch, 0, 0);
      ctx.restore();
    });
    ctx.restore();
  };

  // Top arc: NAND VIDHYA EDUCATION ACADEMY (NVEA)
  drawCurvedText(
    '★ NAND VIDHYA EDUCATION ACADEMY (NVEA) ★',
    167,
    -Math.PI * 0.88,
    -Math.PI * 0.12,
    false
  );

  // Bottom arc: ADMISSION CONFIRMED • SINCE 2006
  drawCurvedText(
    '• ADMISSION CONFIRMED • SINCE 2006 •',
    167,
    Math.PI * 0.84,
    Math.PI * 0.16,
    true
  );

  // Center NVEA Identity inside inner circle
  ctx.textAlign = 'center';
  ctx.font = 'bold 38px "Plus Jakarta Sans", Georgia, serif';
  ctx.fillStyle = '#F27A24';
  ctx.fillText('N', cx - 44, cy - 68);
  ctx.fillStyle = '#93278F';
  ctx.fillText('VEA', cx + 14, cy - 68);

  // Cyan bar & Hindi नव्या
  ctx.fillStyle = '#008FD5';
  ctx.fillRect(cx - 72, cy - 60, 144, 5);
  ctx.font = 'bold 30px "Noto Sans Devanagari", sans-serif';
  ctx.fillText('नव्या', cx, cy - 30);

  // Central green ribbon banner: ADMISSION CONFIRMED & OTP VERIFIED
  ctx.fillStyle = '#047857';
  ctx.fillRect(cx - 178, cy - 16, 356, 38);
  ctx.strokeStyle = '#F59E0B';
  ctx.lineWidth = 2;
  ctx.strokeRect(cx - 178, cy - 16, 356, 38);

  ctx.fillStyle = '#FFFFFF';
  ctx.font = 'bold 17px "Plus Jakarta Sans", sans-serif';
  ctx.fillText('✓ ADMISSION CONFIRMED', cx, cy + 8);

  // Below ribbon: OTP VERIFIED + Date + Verification ID
  ctx.fillStyle = '#991B1B';
  ctx.font = 'bold 15px "Plus Jakarta Sans", sans-serif';
  ctx.fillText('OTP VERIFIED & APPROVED', cx, cy + 44);

  ctx.fillStyle = '#0F2942';
  ctx.font = 'bold 12.5px "JetBrains Mono", monospace';
  ctx.fillText(`DATE: ${payload.verificationDateIst}`, cx, cy + 66);

  ctx.fillStyle = '#475569';
  ctx.font = '600 11px "JetBrains Mono", monospace';
  ctx.fillText(`REF: ${payload.recordNumber}`, cx, cy + 86);

  ctx.fillStyle = '#5B21B6';
  ctx.font = 'italic bold 12px Georgia, serif';
  ctx.fillText('Authorized Digital Seal • NVEA', cx, cy + 108);

  ctx.restore();
  return canvas.toDataURL('image/png');
}
